################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/hw/driver/cdc.c \
../src/hw/driver/cli.c \
../src/hw/driver/flash.c \
../src/hw/driver/led.c \
../src/hw/driver/reset.c \
../src/hw/driver/rtc.c \
../src/hw/driver/uart.c \
../src/hw/driver/usb.c 

OBJS += \
./src/hw/driver/cdc.o \
./src/hw/driver/cli.o \
./src/hw/driver/flash.o \
./src/hw/driver/led.o \
./src/hw/driver/reset.o \
./src/hw/driver/rtc.o \
./src/hw/driver/uart.o \
./src/hw/driver/usb.o 

C_DEPS += \
./src/hw/driver/cdc.d \
./src/hw/driver/cli.d \
./src/hw/driver/flash.d \
./src/hw/driver/led.d \
./src/hw/driver/reset.d \
./src/hw/driver/rtc.d \
./src/hw/driver/uart.d \
./src/hw/driver/usb.d 


# Each subdirectory must supply rules for building sources it contributes
src/hw/driver/cdc.o: ../src/hw/driver/cdc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/cdc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/hw/driver/cli.o: ../src/hw/driver/cli.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/cli.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/hw/driver/flash.o: ../src/hw/driver/flash.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/hw/driver/led.o: ../src/hw/driver/led.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/led.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/hw/driver/reset.o: ../src/hw/driver/reset.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/reset.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/hw/driver/rtc.o: ../src/hw/driver/rtc.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/rtc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/hw/driver/uart.o: ../src/hw/driver/uart.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/uart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
src/hw/driver/usb.o: ../src/hw/driver/usb.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m3 -std=gnu11 -g3 -DSTM32F103xE -c -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/ap" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/bsp" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/core" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/common/hw/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/hw" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/CMSIS/Device/ST/STM32F1xx/Include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Drivers/STM32F1xx_HAL_Driver/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/App" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/cubemx_f103v/USB_DEVICE/Target" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/CMSIS_RTOS" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/include" -I"D:/stm32f103v_cubeide/exam/18_FreeRTOS/src/lib/FreeRTOS/Source/portable/GCC/ARM_CM3" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"src/hw/driver/usb.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

